/**
 * FARERT WASM Wrapper
 * TypeScript wrapper for WebAssembly module initialization
 */

import type { Farert as FaretClass } from '../types/farert';

// Emscripten module interface
interface FaretModule extends EmscriptenModule {
  Farert: new () => FaretClass;
  openDatabase: () => string;
  closeDatabase: () => void;

  // UI functions
  getPrefects: () => string;
  getCompanys: () => string;
  getLinesByPrefect: (prefecture: string) => string;
  getLinesByCompany: (company: string) => string;
  getLinesByStation: (station: string) => string;
  getStationsByCompanyAndLine: (jrgroup: string, lineName: string) => string;
  getStationsByPrefectureAndLine: (prefecture: string, lineName: string) => string;
  getPrefectureByStation: (stationName: string) => string;
  getKanaByStation: (stationName: string) => string;
  searchStationByKeyword: (keyword: string) => string;
  getBranchStationsByLine: (lineName: string, stationName: string) => string;
  getStationsByLine: (lineName: string) => string;
  getPrefectId: (prefecture: string) => number;
  getCompanyId: (company: string) => number;
}

let wasmModule: FaretModule | null = null;
let initPromise: Promise<FaretModule> | null = null;

/**
 * Initialize the FARERT WASM module
 * Must be called before using any FARERT functions
 */
export async function initFarert(): Promise<void> {
  if (wasmModule) {
    return; // Already initialized
  }

  if (initPromise) {
    await initPromise;
    return;
  }

  initPromise = (async () => {
    try {
      // Import the Emscripten-generated module
      // This will be generated by the build process
      const createModule = await import('../../../dist/farert.js').then(
        (m) => m.default || m
      );

      const module = await createModule();
      wasmModule = module as FaretModule;

      // Auto-open database on initialization
      const dbStatus = wasmModule.openDatabase();
      console.log('[FARERT] Database initialized:', dbStatus);

      return wasmModule;
    } catch (error) {
      initPromise = null;
      throw new Error(`Failed to initialize FARERT WASM: ${error}`);
    }
  })();

  await initPromise;
}

/**
 * Get the initialized WASM module
 * @throws Error if module not initialized
 */
function getModule(): FaretModule {
  if (!wasmModule) {
    throw new Error(
      'FARERT WASM not initialized. Call initFarert() first.'
    );
  }
  return wasmModule;
}

/**
 * Farert class wrapper
 * Main interface for route calculation and fare information
 */
export class Farert {
  private instance: FaretClass;

  constructor() {
    const module = getModule();
    this.instance = new module.Farert();
  }

  // Route building methods
  addStartRoute(station: string): number {
    return this.instance.addStartRoute(station);
  }

  addRoute(line: string, station: string): number {
    return this.instance.addRoute(line, station);
  }

  autoRoute(useBulletTrain: number, destinationStation: string): number {
    return this.instance.autoRoute(useBulletTrain, destinationStation);
  }

  getRouteCount(): number {
    return this.instance.getRouteCount();
  }

  departureStationName(): string {
    return this.instance.departureStationName();
  }

  arrivevalStationName(): string {
    return this.instance.arrivevalStationName();
  }

  buildRoute(routeStr: string): number {
    return this.instance.buildRoute(routeStr);
  }

  routeScript(): string {
    return this.instance.routeScript();
  }

  // Route manipulation
  removeAll(): void {
    this.instance.removeAll();
  }

  removeTail(): void {
    this.instance.removeTail();
  }

  reverse(): number {
    return this.instance.reverse();
  }

  // Route configuration
  typeOfPassedLine(offset: number): number {
    return this.instance.typeOfPassedLine(offset);
  }

  setDetour(enabled: boolean): number {
    return this.instance.setDetour(enabled);
  }

  setNoRule(noRule: boolean): void {
    this.instance.setNoRule(noRule);
  }

  // Fare calculation
  showFare(): string {
    return this.instance.showFare();
  }

  // Route flags
  setLongRoute(flag: boolean): void {
    this.instance.setLongRoute(flag);
  }

  setJrTokaiStockApply(flag: boolean): void {
    this.instance.setJrTokaiStockApply(flag);
  }

  setStartAsCity(): void {
    this.instance.setStartAsCity();
  }

  setArrivalAsCity(): void {
    this.instance.setArrivalAsCity();
  }

  setSpecificTermRule115(flag: boolean): void {
    this.instance.setSpecificTermRule115(flag);
  }

  // Route status checks
  isNotSameKokuraHakataShinZai(): boolean {
    return this.instance.isNotSameKokuraHakataShinZai();
  }

  isAvailableReverse(): boolean {
    return this.instance.isAvailableReverse();
  }

  isOsakakanDetourEnable(): boolean {
    return this.instance.isOsakakanDetourEnable();
  }

  isOsakakanDetour(): boolean {
    return this.instance.isOsakakanDetour();
  }

  setNotSameKokuraHakataShinZai(enabled: boolean): void {
    this.instance.setNotSameKokuraHakataShinZai(enabled);
  }

  // JSON serialization
  getFareInfoObjectJson(): string {
    return this.instance.getFareInfoObjectJson();
  }

  getRoutesJson(): string {
    return this.instance.getRoutesJson();
  }

  getRouteRecord(index: number): string {
    return this.instance.getRouteRecord(index);
  }
}

/**
 * Database operations
 */
export function openDatabase(): string {
  return getModule().openDatabase();
}

export function closeDatabase(): void {
  getModule().closeDatabase();
}

/**
 * UI Helper Functions
 */
export function getPrefects(): string {
  return getModule().getPrefects();
}

export function getCompanys(): string {
  return getModule().getCompanys();
}

export function getLinesByPrefect(prefecture: string): string {
  return getModule().getLinesByPrefect(prefecture);
}

export function getLinesByCompany(company: string): string {
  return getModule().getLinesByCompany(company);
}

export function getLinesByStation(station: string): string {
  return getModule().getLinesByStation(station);
}

export function getStationsByCompanyAndLine(jrgroup: string, lineName: string): string {
  return getModule().getStationsByCompanyAndLine(jrgroup, lineName);
}

export function getStationsByPrefectureAndLine(prefecture: string, lineName: string): string {
  return getModule().getStationsByPrefectureAndLine(prefecture, lineName);
}

export function getPrefectureByStation(stationName: string): string {
  return getModule().getPrefectureByStation(stationName);
}

export function getKanaByStation(stationName: string): string {
  return getModule().getKanaByStation(stationName);
}

export function searchStationByKeyword(keyword: string): string {
  return getModule().searchStationByKeyword(keyword);
}

export function getBranchStationsByLine(lineName: string, stationName: string): string {
  return getModule().getBranchStationsByLine(lineName, stationName);
}

export function getStationsByLine(lineName: string): string {
  return getModule().getStationsByLine(lineName);
}

export function getPrefectId(prefecture: string): number {
  return getModule().getPrefectId(prefecture);
}

export function getCompanyId(company: string): number {
  return getModule().getCompanyId(company);
}
