/**
 * FARERT WASM Wrapper
 * TypeScript wrapper for WebAssembly module initialization
 */

import type { Farert as FaretClass } from '../types/farert';
import type { EmscriptenModule } from '../types/emscripten';

// Emscripten module interface
interface FaretModule extends EmscriptenModule {
  Farert: new () => FaretClass;
  openDatabase: () => string;
  closeDatabase: () => void;
  databaseInfo: () => string;

  // UI functions
  getPrefects: () => string;
  getCompanys: () => string;
  getLinesByPrefect: (prefecture: string) => string;
  getLinesByCompany: (company: string) => string;
  getLinesByStation: (station: string) => string;
  getStationsByCompanyAndLine: (jrgroup: string, lineName: string) => string;
  getStationsByPrefectureAndLine: (prefecture: string, lineName: string) => string;
  getPrefectureByStation: (stationName: string) => string;
  getKanaByStation: (stationName: string) => string;
  searchStationByKeyword: (keyword: string) => string;
  getBranchStationsByLine: (lineName: string, includeStationName: string) => string;
  getStationsByLine: (lineName: string) => string;
  getPrefectId: (prefecture: string) => number;
  getCompanyId: (company: string) => number;

  // Developer tools
  executeSql: (sql: string) => string;
}

let wasmModule: FaretModule | null = null;
let initPromise: Promise<FaretModule> | null = null;

/**
 * Initialize the FARERT WASM module
 * Must be called before using any FARERT functions
 */
export async function initFarert(): Promise<void> {
  if (wasmModule) {
    return; // Already initialized
  }

  if (initPromise) {
    await initPromise;
    return;
  }

  initPromise = (async () => {
    try {
      // Import the Emscripten-generated module
      // This will be generated by the build process
      // @ts-ignore - farert.js is generated by Emscripten build
      const createModule = await import('../farert.js').then(
        (m) => m.default || m
      );

      const module = await createModule({
        locateFile: (path: string, prefix: string) => {
          // WASM and data files are in dist/ directory
          // Use absolute URL to avoid path resolution issues
          if (path.endsWith('.wasm') || path.endsWith('.data')) {
            // Get the base URL from window.location
            const baseUrl = typeof window !== 'undefined'
              ? window.location.origin
              : '';
            return `${baseUrl}/dist/${path}`;
          }
          return prefix + path;
        }
      });
      wasmModule = module as FaretModule;

      // Auto-open database on initialization
      const dbStatus = wasmModule.openDatabase();
      console.log('[FARERT] Database initialized:', dbStatus);

      return wasmModule;
    } catch (error) {
      initPromise = null;
      throw new Error(`Failed to initialize FARERT WASM: ${error}`);
    }
  })();

  await initPromise;
}

/**
 * Get the initialized WASM module
 * @throws Error if module not initialized
 */
function getModule(): FaretModule {
  if (!wasmModule) {
    throw new Error(
      'FARERT WASM not initialized. Call initFarert() first.'
    );
  }
  return wasmModule;
}

/**
 * Farert class wrapper
 * Main interface for route calculation and fare information
 */
export class Farert {
  private instance: FaretClass;

  constructor() {
    const module = getModule();
    this.instance = new module.Farert();
  }

  // Route building methods
  addStartRoute(station: string): number {
    return this.instance.addStartRoute(station);
  }

  addRoute(line: string, station: string): number {
    return this.instance.addRoute(line, station);
  }

  autoRoute(useBulletTrain: number, destinationStation: string): number {
    return this.instance.autoRoute(useBulletTrain, destinationStation);
  }

  getRouteCount(): number {
    return this.instance.getRouteCount();
  }

  departureStationName(): string {
    return this.instance.departureStationName();
  }

  arrivevalStationName(): string {
    return this.instance.arrivevalStationName();
  }

  buildRoute(routeStr: string): string {
    return this.instance.buildRoute(routeStr);
  }

  routeScript(): string {
    return this.instance.routeScript();
  }

  // Route manipulation
  removeAll(): void {
    this.instance.removeAll();
  }

  removeTail(): void {
    this.instance.removeTail();
  }

  reverse(): number {
    return this.instance.reverse();
  }

  // Route configuration
  typeOfPassedLine(offset: number): number {
    return this.instance.typeOfPassedLine(offset);
  }

  setDetour(enabled: boolean): number {
    return this.instance.setDetour(enabled);
  }

  setNoRule(noRule: boolean): void {
    this.instance.setNoRule(noRule);
  }

  // Fare calculation
  showFare(): string {
    return this.instance.showFare();
  }

  // Route flags
  setLongRoute(flag: boolean): void {
    this.instance.setLongRoute(flag);
  }

  setJrTokaiStockApply(flag: boolean): void {
    this.instance.setJrTokaiStockApply(flag);
  }

  setStartAsCity(): void {
    this.instance.setStartAsCity();
  }

  setArrivalAsCity(): void {
    this.instance.setArrivalAsCity();
  }

  setSpecificTermRule115(flag: boolean): void {
    this.instance.setSpecificTermRule115(flag);
  }

  // Route status checks
  isNotSameKokuraHakataShinZai(): boolean {
    return this.instance.isNotSameKokuraHakataShinZai();
  }

  isAvailableReverse(): boolean {
    return this.instance.isAvailableReverse();
  }

  isOsakakanDetourEnable(): boolean {
    return this.instance.isOsakakanDetourEnable();
  }

  isOsakakanDetour(): boolean {
    return this.instance.isOsakakanDetour();
  }

  setNotSameKokuraHakataShinZai(enabled: boolean): void {
    this.instance.setNotSameKokuraHakataShinZai(enabled);
  }

  // JSON serialization
  getFareInfoObjectJson(): string {
    return this.instance.getFareInfoObjectJson();
  }

  getRoutesJson(): string {
    return this.instance.getRoutesJson();
  }

  getRouteRecord(index: number): string {
    return this.instance.getRouteRecord(index);
  }
}

/**
 * Database operations
 */
export function openDatabase(): string {
  return getModule().openDatabase();
}

export function closeDatabase(): void {
  getModule().closeDatabase();
}

/**
 * Get database information
 * Returns JSON string with database name and creation date
 *
 * @returns JSON string with database metadata
 *
 * @example
 * ```typescript
 * const info = databaseInfo();
 * const data = JSON.parse(info);
 * console.log('DB Name:', data.dbName);
 * console.log('Created:', data.createdate);
 * ```
 */
export function databaseInfo(): string {
  return getModule().databaseInfo();
}

/**
 * UI Helper Functions
 */
export function getPrefects(): string {
  return getModule().getPrefects();
}

export function getCompanys(): string {
  return getModule().getCompanys();
}

export function getLinesByPrefect(prefecture: string): string {
  return getModule().getLinesByPrefect(prefecture);
}

export function getLinesByCompany(company: string): string {
  return getModule().getLinesByCompany(company);
}

export function getLinesByStation(station: string): string {
  return getModule().getLinesByStation(station);
}

export function getStationsByCompanyAndLine(jrgroup: string, lineName: string): string {
  return getModule().getStationsByCompanyAndLine(jrgroup, lineName);
}

export function getStationsByPrefectureAndLine(prefecture: string, lineName: string): string {
  return getModule().getStationsByPrefectureAndLine(prefecture, lineName);
}

export function getPrefectureByStation(stationName: string): string {
  return getModule().getPrefectureByStation(stationName);
}

export function getKanaByStation(stationName: string): string {
  return getModule().getKanaByStation(stationName);
}

export function searchStationByKeyword(keyword: string): string {
  return getModule().searchStationByKeyword(keyword);
}

export function getBranchStationsByLine(lineName: string, includeStationName: string): string {
  return getModule().getBranchStationsByLine(lineName, includeStationName);
}

export function getStationsByLine(lineName: string): string {
  return getModule().getStationsByLine(lineName);
}

export function getPrefectId(prefecture: string): number {
  return getModule().getPrefectId(prefecture);
}

export function getCompanyId(company: string): number {
  return getModule().getCompanyId(company);
}

/**
 * Developer Tools
 */

/**
 * Execute arbitrary SQL query and return results as JSON
 * For debugging and development only
 *
 * @param sql - SQL query to execute
 * @returns JSON string with query results
 *
 * @example
 * ```typescript
 * const result = executeSql("SELECT * FROM t_station WHERE name='東京'");
 * const data = JSON.parse(result);
 * console.log(data.rows);
 * ```
 */
export function executeSql(sql: string): string {
  return getModule().executeSql(sql);
}

/**
 * Type definition for SQL query result
 */
export interface SqlResult {
  columns: string[];
  rows: any[][];
  rowCount: number;
  error?: string;
}

/**
 * Type definition for database information
 */
export interface DatabaseInfo {
  result: boolean;
  dbName?: string;
  createdate?: string;
  reason?: string;
}

/**
 * Type definition for buildRoute result
 */
export interface BuildRouteResult {
  /** Result code (0 = success, negative = error) */
  rc: number;
  /** Failed item (station/line name that caused error) */
  failItem: string;
  /** Offset of word in route string where error occurred (0-based) */
  offset: number;
}
