/**
 * C++ Compatibility Validation Framework
 * Task 20 - Final CLI Integration Testing and Compatibility Validation
 * 
 * This module provides comprehensive validation to ensure 100% compatibility
 * between TypeScript CLI implementation and original C++ testmain.cpp/test_exec.cpp
 * 
 * Requirements:
 * - REQ-CLI-001: testmain.cpp argument parsing and command behavior
 * - REQ-CLI-002: test_exec.cpp test execution order and results (±0円tolerance)
 * - REQ-CLI-003: Error handling and Japanese text processing
 */

import * as fs from 'fs';
import * as path from 'path';

/**
 * C++ compatibility reference data and expected results
 * Based on original testmain.cpp and test_exec.cpp behavior
 */

/**
 * Expected C++ testmain.cpp command behaviors
 */
export interface CppCommandBehavior {
  command: string[];
  expectedExitCode: number;
  expectedOutputPatterns: string[];
  forbiddenOutputPatterns: string[];
  description: string;
  cppSource: string; // Reference to C++ source location
}

/**
 * Expected fare calculation results from C++ implementation
 * These would be generated by running the actual C++ version
 */
export interface CppFareResult {
  route: string;
  expectedFare: number;
  fareString: string;
  specialRules?: string[];
  tolerance: number; // Should be 0 for exact compatibility
}

/**
 * Test execution order from test_exec.cpp
 * CRITICAL: Order must match exactly for result comparison
 */
export interface CppTestExecutionOrder {
  testNumber: number;
  testName: string;
  routeDefinition: string;
  expectedOutput: string;
  testGroup: string;
}

/**
 * C++ compatibility validation result
 */
export interface CppCompatibilityResult {
  compatible: boolean;
  testName: string;
  category: 'argument_parsing' | 'fare_calculation' | 'test_execution' | 'error_handling' | 'japanese_text';
  
  // Comparison results
  exitCodeMatch: boolean;
  outputPatternMatch: boolean;
  fareAccuracyMatch: boolean;
  testOrderMatch: boolean;
  
  // Detailed analysis
  differences: string[];
  suggestions: string[];
  
  // Performance comparison
  performanceComparison?: {
    cppTime?: number;
    tsTime: number;
    acceptable: boolean;
  };
}

/**
 * C++ Compatibility Validator Class
 */
export class CppCompatibilityValidator {
  private cppCommandBehaviors: CppCommandBehavior[];
  private cppFareResults: CppFareResult[];
  private cppTestExecutionOrder: CppTestExecutionOrder[];
  
  constructor() {
    this.initializeCppReferenceData();
  }
  
  /**
   * Initialize reference data from C++ implementation
   * In production, this would be populated from actual C++ test runs
   */
  private initializeCppReferenceData(): void {
    // C++ testmain.cpp command behaviors
    this.cppCommandBehaviors = [
      {
        command: ['-h'],
        expectedExitCode: 0,
        expectedOutputPatterns: [
          'Usage:',
          'OPTIONS:',
          '-exec',
          '-5',
          'EXAMPLES:'
        ],
        forbiddenOutputPatterns: [
          'Error:',
          'undefined',
          'null',
          'TypeError'
        ],
        description: 'Help command displays usage information',
        cppSource: 'testmain.cpp:printUsage()'
      },
      {
        command: ['--help'],
        expectedExitCode: 0,
        expectedOutputPatterns: [
          'Usage:',
          'OPTIONS:',
          'EXAMPLES:'
        ],
        forbiddenOutputPatterns: [
          'Error:',
          'Command not found'
        ],
        description: 'Long help command works identically to -h',
        cppSource: 'testmain.cpp:main() help processing'
      },
      {
        command: ['-help'],
        expectedExitCode: 0,
        expectedOutputPatterns: [
          'Usage:',
          'OPTIONS:'
        ],
        forbiddenOutputPatterns: [
          'Error:',
          'Invalid option'
        ],
        description: 'Alternative help command format',
        cppSource: 'testmain.cpp:main() help processing'
      },
      {
        command: ['-5', '東京', '東海道線', '品川', '山手線', '新宿'],
        expectedExitCode: 0,
        expectedOutputPatterns: [
          '東京',
          '品川',
          '新宿',
          '東海道線',
          '山手線',
          '円' // Fare result
        ],
        forbiddenOutputPatterns: [
          'Error:',
          'Station not found',
          'Invalid'
        ],
        description: '5-parameter route calculation',
        cppSource: 'testmain.cpp:handle5ParameterRoute equivalent'
      },
      {
        command: ['-exec'],
        expectedExitCode: 0,
        expectedOutputPatterns: [
          'test suite',
          'Test 1',
          'Test 2',
          'Test 3',
          'Test 4',
          'Test 5',
          'Test 6',
          'Test 7',
          'Test 8'
        ],
        forbiddenOutputPatterns: [
          'Error:',
          'Failed to initialize',
          'Database error'
        ],
        description: 'Complete test suite execution',
        cppSource: 'test_exec.cpp:test_exec() function'
      }
    ];
    
    // Expected fare calculation results (would be populated from C++ runs)
    this.cppFareResults = [
      {
        route: '東京 東海道線 品川',
        expectedFare: 160, // Example fare - would be actual C++ result
        fareString: '160円',
        tolerance: 0, // ±0円requirement
      },
      {
        route: '東京 東海道線 品川 山手線 新宿',
        expectedFare: 200, // Example fare - would be actual C++ result
        fareString: '200円',
        tolerance: 0, // ±0円requirement
      },
      {
        route: '新宿 中央線 立川',
        expectedFare: 290, // Example fare - would be actual C++ result
        fareString: '290円',
        tolerance: 0, // ±0円requirement
      },
      {
        route: '大阪 東海道線 京都',
        expectedFare: 560, // Example fare - would be actual C++ result
        fareString: '560円',
        tolerance: 0, // ±0円requirement
      }
    ];
    
    // Test execution order from test_exec.cpp (CRITICAL: exact order)
    this.cppTestExecutionOrder = [
      {
        testNumber: 1,
        testName: 'testRoute2',
        routeDefinition: 'testRoute2Tbl entries',
        expectedOutput: 'Test 1: testRoute2',
        testGroup: 'testRoute2'
      },
      {
        testNumber: 2,
        testName: 'jctSpecialRoute',
        routeDefinition: 'jctSpecialRouteTbl entries',
        expectedOutput: 'Test 2: jctSpecialRoute',
        testGroup: 'jctSpecialRoute'
      },
      {
        testNumber: 3,
        testName: 'hzlRoute',
        routeDefinition: 'hzlRouteDef entries',
        expectedOutput: 'Test 3: hzlRoute',
        testGroup: 'hzlRoute'
      },
      {
        testNumber: 4,
        testName: 'hzlDef',
        routeDefinition: 'hzlDefTbl entries',
        expectedOutput: 'Test 4: hzlDef',
        testGroup: 'hzlDef'
      },
      {
        testNumber: 5,
        testName: 'testRoute',
        routeDefinition: 'testRouteTbl entries',
        expectedOutput: 'Test 5: testRoute',
        testGroup: 'testRoute'
      },
      {
        testNumber: 6,
        testName: 'testShin2Zai',
        routeDefinition: 'testShin2ZaiTbl entries',
        expectedOutput: 'Test 6: testShin2Zai',
        testGroup: 'testShin2Zai'
      },
      {
        testNumber: 7,
        testName: 'testRoute3',
        routeDefinition: 'testRoute3Tbl entries',
        expectedOutput: 'Test 7: testRoute3',
        testGroup: 'testRoute3'
      },
      {
        testNumber: 8,
        testName: 'longRouteTest',
        routeDefinition: 'longRouteTestTbl entries',
        expectedOutput: 'Test 8: longRoute',
        testGroup: 'longRoute'
      }
    ];
  }
  
  /**
   * Validate command behavior against C++ testmain.cpp
   */
  public validateCommandBehavior(
    command: string[],
    actualExitCode: number,
    actualOutput: string,
    actualStderr: string
  ): CppCompatibilityResult {
    const behavior = this.cppCommandBehaviors.find(b => 
      JSON.stringify(b.command) === JSON.stringify(command)
    );
    
    if (!behavior) {
      return {
        compatible: false,
        testName: `Unknown command: ${command.join(' ')}`,
        category: 'argument_parsing',
        exitCodeMatch: false,
        outputPatternMatch: false,
        fareAccuracyMatch: false,
        testOrderMatch: false,
        differences: ['Command not found in C++ reference data'],
        suggestions: ['Add command to C++ reference data or verify command syntax']
      };
    }
    
    const result: CppCompatibilityResult = {
      compatible: true,
      testName: behavior.description,
      category: 'argument_parsing',
      exitCodeMatch: actualExitCode === behavior.expectedExitCode,
      outputPatternMatch: true,
      fareAccuracyMatch: true,
      testOrderMatch: true,
      differences: [],
      suggestions: []
    };
    
    // Validate exit code
    if (!result.exitCodeMatch) {
      result.compatible = false;
      result.differences.push(
        `Exit code mismatch: expected ${behavior.expectedExitCode}, got ${actualExitCode}`
      );
      result.suggestions.push('Check error handling and return codes match C++ implementation');
    }
    
    // Validate expected output patterns
    const combinedOutput = actualOutput + actualStderr;
    for (const pattern of behavior.expectedOutputPatterns) {
      if (!combinedOutput.includes(pattern)) {
        result.compatible = false;
        result.outputPatternMatch = false;
        result.differences.push(`Missing expected output pattern: "${pattern}"`);
        result.suggestions.push(`Ensure output contains: "${pattern}"`);
      }
    }
    
    // Validate forbidden output patterns
    for (const pattern of behavior.forbiddenOutputPatterns) {
      if (combinedOutput.includes(pattern)) {
        result.compatible = false;
        result.outputPatternMatch = false;
        result.differences.push(`Found forbidden output pattern: "${pattern}"`);
        result.suggestions.push(`Remove or fix output containing: "${pattern}"`);
      }
    }
    
    return result;
  }
  
  /**
   * Validate fare calculation against C++ results
   * CRITICAL: ±0円tolerance requirement
   */
  public validateFareCalculation(
    route: string,
    actualFare: number,
    actualFareString: string
  ): CppCompatibilityResult {
    const expectedResult = this.cppFareResults.find(r => r.route === route);
    
    if (!expectedResult) {
      return {
        compatible: false,
        testName: `Fare validation: ${route}`,
        category: 'fare_calculation',
        exitCodeMatch: true,
        outputPatternMatch: true,
        fareAccuracyMatch: false,
        testOrderMatch: true,
        differences: ['No C++ reference fare found for route'],
        suggestions: ['Add route to C++ reference data by running C++ version']
      };
    }
    
    const result: CppCompatibilityResult = {
      compatible: true,
      testName: `Fare calculation: ${route}`,
      category: 'fare_calculation',
      exitCodeMatch: true,
      outputPatternMatch: true,
      fareAccuracyMatch: true,
      testOrderMatch: true,
      differences: [],
      suggestions: []
    };
    
    // Validate fare accuracy with ±0円tolerance
    const fareDifference = Math.abs(actualFare - expectedResult.expectedFare);
    if (fareDifference > expectedResult.tolerance) {
      result.compatible = false;
      result.fareAccuracyMatch = false;
      result.differences.push(
        `Fare calculation error: expected ${expectedResult.expectedFare}円, ` +
        `got ${actualFare}円 (difference: ${fareDifference}円, ` +
        `tolerance: ${expectedResult.tolerance}円)`
      );
      result.suggestions.push('Review fare calculation logic for exact C++ compatibility');
      result.suggestions.push('Check database data consistency with C++ version');
      result.suggestions.push('Verify special fare rules are implemented correctly');
    }
    
    // Validate fare string format
    if (actualFareString !== expectedResult.fareString) {
      result.compatible = false;
      result.outputPatternMatch = false;
      result.differences.push(
        `Fare string format mismatch: expected "${expectedResult.fareString}", ` +
        `got "${actualFareString}"`
      );
      result.suggestions.push('Match fare string format exactly to C++ output');
    }
    
    return result;
  }
  
  /**
   * Validate test execution order against test_exec.cpp
   * CRITICAL: Order must match exactly
   */
  public validateTestExecutionOrder(
    actualTestOutput: string
  ): CppCompatibilityResult {
    const result: CppCompatibilityResult = {
      compatible: true,
      testName: 'Test execution order validation',
      category: 'test_execution',
      exitCodeMatch: true,
      outputPatternMatch: true,
      fareAccuracyMatch: true,
      testOrderMatch: true,
      differences: [],
      suggestions: []
    };
    
    // Check that tests appear in correct order
    let lastFoundIndex = -1;
    for (const testOrder of this.cppTestExecutionOrder) {
      const currentIndex = actualTestOutput.indexOf(testOrder.expectedOutput);
      
      if (currentIndex === -1) {
        result.compatible = false;
        result.testOrderMatch = false;
        result.differences.push(`Missing expected test output: "${testOrder.expectedOutput}"`);
        result.suggestions.push(`Ensure test ${testOrder.testNumber} (${testOrder.testName}) is executed`);
        continue;
      }
      
      if (currentIndex <= lastFoundIndex) {
        result.compatible = false;
        result.testOrderMatch = false;
        result.differences.push(
          `Test order violation: ${testOrder.testName} appears before previous test`
        );
        result.suggestions.push(
          `Ensure test execution order matches test_exec.cpp exactly: ` +
          `${this.cppTestExecutionOrder.map(t => t.testName).join(' → ')}`
        );
      }
      
      lastFoundIndex = currentIndex;
    }
    
    return result;
  }
  
  /**
   * Validate Japanese text processing and display
   */
  public validateJapaneseText(
    input: string,
    actualOutput: string
  ): CppCompatibilityResult {
    const result: CppCompatibilityResult = {
      compatible: true,
      testName: 'Japanese text processing validation',
      category: 'japanese_text',
      exitCodeMatch: true,
      outputPatternMatch: true,
      fareAccuracyMatch: true,
      testOrderMatch: true,
      differences: [],
      suggestions: []
    };
    
    // Check UTF-8 encoding preservation
    const japanesePattern = /[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF]/;
    if (japanesePattern.test(input) && !japanesePattern.test(actualOutput)) {
      result.compatible = false;
      result.outputPatternMatch = false;
      result.differences.push('Japanese characters not preserved in output');
      result.suggestions.push('Check UTF-8 encoding handling');
      result.suggestions.push('Ensure Japanese text is properly displayed');
    }
    
    // Check for mojibake (character corruption)
    const mojibakePatterns = [
      /\?{2,}/, // Multiple question marks
      /[\uFFFD]/, // Unicode replacement character
      /\\u[0-9a-fA-F]{4}/, // Escaped Unicode
      /&#\d+;/ // HTML entities
    ];
    
    for (const pattern of mojibakePatterns) {
      if (pattern.test(actualOutput)) {
        result.compatible = false;
        result.outputPatternMatch = false;
        result.differences.push('Potential character encoding corruption detected');
        result.suggestions.push('Review character encoding handling');
        break;
      }
    }
    
    return result;
  }
  
  /**
   * Validate error handling against C++ patterns
   */
  public validateErrorHandling(
    errorScenario: string,
    actualExitCode: number,
    actualOutput: string,
    actualStderr: string
  ): CppCompatibilityResult {
    const result: CppCompatibilityResult = {
      compatible: true,
      testName: `Error handling: ${errorScenario}`,
      category: 'error_handling',
      exitCodeMatch: true,
      outputPatternMatch: true,
      fareAccuracyMatch: true,
      testOrderMatch: true,
      differences: [],
      suggestions: []
    };
    
    // Define expected error behaviors based on C++ implementation
    const expectedErrorBehaviors = {
      'invalid_station': {
        expectedExitCode: -1,
        shouldContain: ['Station not found', 'Invalid'],
        shouldNotContain: ['undefined', 'TypeError', 'Error:']
      },
      'invalid_line': {
        expectedExitCode: -1,
        shouldContain: ['Invalid line', 'Line not found'],
        shouldNotContain: ['undefined', 'TypeError']
      },
      'parameter_count_mismatch': {
        expectedExitCode: -1,
        shouldContain: ['parameter', 'required'],
        shouldNotContain: ['undefined', 'null']
      },
      'missing_database': {
        expectedExitCode: -1,
        shouldContain: ['database', 'not found'],
        shouldNotContain: ['undefined', 'TypeError']
      }
    };
    
    const expected = expectedErrorBehaviors[errorScenario as keyof typeof expectedErrorBehaviors];
    if (!expected) {
      result.differences.push(`Unknown error scenario: ${errorScenario}`);
      return result;
    }
    
    // Validate exit code
    if (actualExitCode !== expected.expectedExitCode) {
      result.compatible = false;
      result.exitCodeMatch = false;
      result.differences.push(
        `Error exit code mismatch: expected ${expected.expectedExitCode}, got ${actualExitCode}`
      );
      result.suggestions.push('Match error exit codes to C++ implementation');
    }
    
    // Validate error message content
    const combinedOutput = actualOutput + actualStderr;
    
    for (const shouldContain of expected.shouldContain) {
      if (!combinedOutput.toLowerCase().includes(shouldContain.toLowerCase())) {
        result.compatible = false;
        result.outputPatternMatch = false;
        result.differences.push(`Error message should contain: "${shouldContain}"`);
        result.suggestions.push(`Include "${shouldContain}" in error messages`);
      }
    }
    
    for (const shouldNotContain of expected.shouldNotContain) {
      if (combinedOutput.includes(shouldNotContain)) {
        result.compatible = false;
        result.outputPatternMatch = false;
        result.differences.push(`Error message should not contain: "${shouldNotContain}"`);
        result.suggestions.push(`Remove "${shouldNotContain}" from error messages`);
      }
    }
    
    return result;
  }
  
  /**
   * Generate comprehensive compatibility report
   */
  public generateCompatibilityReport(results: CppCompatibilityResult[]): string {
    const totalTests = results.length;
    const compatibleTests = results.filter(r => r.compatible).length;
    const compatibilityRate = (compatibleTests / totalTests) * 100;
    
    const categorySummary = {
      argument_parsing: results.filter(r => r.category === 'argument_parsing'),
      fare_calculation: results.filter(r => r.category === 'fare_calculation'),
      test_execution: results.filter(r => r.category === 'test_execution'),
      error_handling: results.filter(r => r.category === 'error_handling'),
      japanese_text: results.filter(r => r.category === 'japanese_text')
    };
    
    let report = `# C++ Compatibility Validation Report\n\n`;
    report += `**Overall Compatibility: ${compatibilityRate.toFixed(1)}%**\n`;
    report += `**Compatible Tests: ${compatibleTests}/${totalTests}**\n\n`;
    
    report += `## Category Summary\n\n`;
    for (const [category, categoryResults] of Object.entries(categorySummary)) {
      const categoryCompatible = categoryResults.filter(r => r.compatible).length;
      const categoryTotal = categoryResults.length;
      const categoryRate = categoryTotal > 0 ? (categoryCompatible / categoryTotal) * 100 : 100;
      
      report += `### ${category.replace('_', ' ').toUpperCase()}\n`;
      report += `- Compatibility: ${categoryRate.toFixed(1)}% (${categoryCompatible}/${categoryTotal})\n\n`;
    }
    
    report += `## Failed Compatibility Tests\n\n`;
    const failedTests = results.filter(r => !r.compatible);
    if (failedTests.length === 0) {
      report += `✅ All tests passed C++ compatibility validation!\n\n`;
    } else {
      for (const failed of failedTests) {
        report += `### ❌ ${failed.testName}\n`;
        report += `**Category:** ${failed.category}\n\n`;
        
        if (failed.differences.length > 0) {
          report += `**Differences:**\n`;
          for (const diff of failed.differences) {
            report += `- ${diff}\n`;
          }
          report += `\n`;
        }
        
        if (failed.suggestions.length > 0) {
          report += `**Suggestions:**\n`;
          for (const suggestion of failed.suggestions) {
            report += `- ${suggestion}\n`;
          }
          report += `\n`;
        }
      }
    }
    
    report += `## Requirements Status\n\n`;
    report += `- **REQ-CLI-001 (testmain.cpp compatibility):** ${categorySummary.argument_parsing.every(r => r.compatible) ? '✅ PASSED' : '❌ FAILED'}\n`;
    report += `- **REQ-CLI-002 (fare calculation ±0円):** ${categorySummary.fare_calculation.every(r => r.compatible) ? '✅ PASSED' : '❌ FAILED'}\n`;
    report += `- **REQ-CLI-002 (test_exec.cpp order):** ${categorySummary.test_execution.every(r => r.compatible) ? '✅ PASSED' : '❌ FAILED'}\n`;
    report += `- **REQ-CLI-003 (error handling):** ${categorySummary.error_handling.every(r => r.compatible) ? '✅ PASSED' : '❌ FAILED'}\n`;
    report += `- **REQ-CLI-003 (Japanese text):** ${categorySummary.japanese_text.every(r => r.compatible) ? '✅ PASSED' : '❌ FAILED'}\n\n`;
    
    const overallCompatible = compatibilityRate === 100;
    report += `## Final Assessment\n\n`;
    report += `**100% C++ Compatibility Requirement: ${overallCompatible ? '✅ ACHIEVED' : '❌ NOT ACHIEVED'}**\n\n`;
    
    if (!overallCompatible) {
      report += `⚠️  **Action Required:** Address ${totalTests - compatibleTests} compatibility issues before Task 20 completion.\n\n`;
    } else {
      report += `🎉 **Task 20 Ready:** All C++ compatibility requirements have been met!\n\n`;
    }
    
    return report;
  }
  
  /**
   * Load expected C++ results from file (if available)
   * This would be populated by running the actual C++ implementation
   */
  public loadCppResultsFromFile(filePath: string): void {
    try {
      if (fs.existsSync(filePath)) {
        const data = fs.readFileSync(filePath, 'utf8');
        const cppResults = JSON.parse(data);
        
        if (cppResults.commands) {
          this.cppCommandBehaviors = cppResults.commands;
        }
        
        if (cppResults.fares) {
          this.cppFareResults = cppResults.fares;
        }
        
        if (cppResults.testOrder) {
          this.cppTestExecutionOrder = cppResults.testOrder;
        }
      }
    } catch (error) {
      console.warn(`Warning: Could not load C++ results from ${filePath}:`, error);
    }
  }
  
  /**
   * Save actual TypeScript results for comparison
   */
  public saveTsResultsForComparison(
    results: any[],
    outputPath: string
  ): void {
    try {
      const outputData = {
        timestamp: new Date().toISOString(),
        nodeVersion: process.version,
        platform: process.platform,
        results: results
      };
      
      fs.writeFileSync(outputPath, JSON.stringify(outputData, null, 2), 'utf8');
    } catch (error) {
      console.error(`Failed to save TypeScript results to ${outputPath}:`, error);
    }
  }
}